<h1>Intro to numpy</h1>

<p>
    <h3>Differences between lists and NumPy Arrays</h3>
    <ul>
        <li>An array's size is immutable. You cannot append, insert or remove elements, like you can with a list.</li>
        <li>All of an array's elements must be of the same data type.</li>
        <li>A NumPy array behaves in a Pythonic fashion. You can len(my_array) just like you would assume.</li>
    </ul>
</p>

<p>
<h3>Properties of numpy:</h3>
    <ul>
        <li>n-Dimensional</li>
        <li>Homogenous - Only one data type</li>
        <li>Vectorization</li>
        <li>Broadcasting</li>
    </ul>
</p></p6

<h5>Use "pip install numpy" command if  is not installed<h6></h5>

In [39]:
np.__version__ #to check the version

'1.26.4'

In [24]:
import numpy as np #importing numpy

In [25]:
## creation of array 1D 
arr = np.array([25,41,63,66,85,74])
arr 

array([25, 41, 63, 66, 85, 74])

In [26]:
type(arr)
# ndarray  ==> n diminensional array 

numpy.ndarray

In [27]:
arr.size  # no. of  item 

6

In [28]:
#same as size
len(arr)

6

In [29]:
arr.ndim   # to check the dimension of array 

1

In [30]:
arr = np.array([25,41,63,66,85,74,25.01,'upflairs',True])
arr   
## array stores similar item 

array(['25', '41', '63', '66', '85', '74', '25.01', 'upflairs', 'True'],
      dtype='<U32')

In [31]:
#data type
arr.dtype

dtype('<U32')

In [56]:

ls = [25,41,63,66,85,74]
arr = np.array(ls) #converting list into array
arr

array([25, 41, 63, 66, 85, 74])

In [57]:
#elements of array can be fetched by negative indexing also
arr[-1]

74

In [58]:
#slicing
arr[::] #by default start = 0  , stoping  = end , jump == 1 

array([25, 41, 63, 66, 85, 74])

In [59]:
#values can be changed
arr[-1] = 500
arr

array([ 25,  41,  63,  66,  85, 500])

In [60]:
arr + 2 #vectorizaton - add number to each elements

array([ 27,  43,  65,  68,  87, 502])

In [41]:
arr * 2

array([  50,   82,  126,  132,  170, 1000])

In [63]:
ls = [[1,2,3],
     [4,5,6],
     [7,8,9]]

type(ls)

list

In [64]:
arr = np.array(ls) #list into array
type(arr)

numpy.ndarray

In [65]:
arr.ndim #shows the dimension of the array

2

In [66]:
arr.shape

(3, 3)

In [67]:
arr * 2 #broadcasting - broadcast to each element

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [71]:
arr + [[2,1,0],
       [3,2,1],
       [4,3,2]] #vectorization - each element interact with same index's element

array([[ 3,  3,  3],
       [ 7,  7,  7],
       [11, 11, 11]])

In [72]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
#arr[row , column ]
arr[0::2,::2] #using start , end , jump find [1 3][7 9] from list

array([[1, 3],
       [7, 9]])

In [113]:
arr[-1,-1]

9

In [117]:
a = np.random.randint(1,10,20)
a # single dimension array , 20 elements randomly set including 1 to excluding 10

array([8, 7, 9, 7, 6, 3, 8, 5, 5, 9, 6, 9, 1, 3, 4, 8, 8, 3, 2, 3])

In [122]:
a2 = a.reshape(5,4) #reshape in into 5*4 matrix
a2

array([[8, 7, 9, 7],
       [6, 3, 8, 5],
       [5, 9, 6, 9],
       [1, 3, 4, 8],
       [8, 3, 2, 3]])

In [126]:
#fetching values less than 5
a2[a2<5]

array([3, 1, 3, 4, 3, 2, 3])

In [128]:
#fetching the size of arr in which values greater and equal to 5 
a2[a2>=5].size

13

In [135]:
np.zeros(20,dtype=int).reshape(2,2,5)
# .zeros(20,dtype=int) - create an array of zeroes having 20 elements integer type

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [145]:
np.ones(20, dtype=int).reshape(4,5)
# .zeros(20,dtype=int) - create an array of ones having 20 elements integer type

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [161]:
np.arange(1,21,2).reshape(5,2)
#arranging an array from 1 to 20 having gap of 2 consecutive no. 

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [167]:
np.linspace(0,20,5) #return an array which have equal 5 parts from 0 to 20

array([ 0.,  5., 10., 15., 20.])

In [174]:
arr3D = [[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]] #3dimensional
a3 = np.array(arr3D)
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [175]:
a3.ndim

3

In [177]:
#[1,2,3]
#[10,11,12]
a3[0:,0,:]

array([[ 1,  2,  3],
       [10, 11, 12]])

In [179]:
np.mean(a3) #returns mean

9.5

In [180]:
np.min(a3) #return minimum

1

In [181]:
np.max(a3) #return maximum

18

In [182]:
np.argmin(a3)
# argmin returns index of minimum item 

0

In [184]:
np.argmax(a3)
# argmax returns index of maximum item 

17

In [187]:
array = np.random.randint(10,30,9)
array

array([11, 27, 19, 14, 16, 25, 24, 11, 24])

In [192]:
array.sort() #sort the array
array

array([11, 11, 14, 16, 19, 24, 24, 25, 27])

<h1>
    Congratulations!
</h1>
<h2>
    Thanks for reading this!!!
</h2>